[pipeline]
steps = ["import_markmap", "enrich_markmap_notes"]  # export happens after this step

[io]
output_dir = "output"
debug_dir  = "debug"

[llm]
provider    = "deepseek"
model       = "deepseek-chat"
api_key_env = "DEEPSEEK_API_KEY"
temperature = 0.2
max_tokens  = 8192
timeout     = 1000000
max_retries = 3

[runtime]
executor_max_workers = 24
min_delay_sec = 0.15
max_retries = 4
